### ISSUE TITLE
Use Bazarr as an alternative ot Sub-Zero

### ISSUE THREAD

**Issue by johnpyp** [sebgl/htpc-download-box#13]
It seems that Sub-Zero is not going to receive any more feature updates and that the lead developer is now starting to contribute to Bazarr instead ([60+ commits to bazarr since October](https://github.com/morpheus65535/bazarr/graphs/contributors?from=2018-09-30&to=2019-04-05&type=c)). 

[Bazarr](https://github.com/morpheus65535/bazarr) is a companion to Sonarr and Radarr that is exclusively for finding subtitles. It has more features than Sub-Zero, and it isn't tied to Plex.

**Comment by sebgl** [comment]
Interesting, I did not know about that one.
I'm wondering how good it is compared to sub-zero for finding subtitles. Did you give it a try?

**Comment by johnpyp** [comment]
I haven't tried it yet, I will today.

**Comment by johnpyp** [comment]
I've been testing it a bit, and it seems fairly consistent, though there are offset problems as is to be expected of subtitle providers. I haven't tried sub-zero at all or compared against it, and I opted to rename all my files rather than keep the original file names so my experience probably isn't a good comparison anyways.

I imagine it is a logical step however, especially since the primary contributor of sub-zero is contributing now to this and stopping feature development on sub-zero.

I have a branch theoretically ready for merging (branched off the previous PR branch, `static-docs`), if you want to try it out: https://github.com/johnpyp/homemedia-docker/tree/feature-bazarr

**Comment by csandman** [comment]
I recently tried Bazarr over sub-zero as sub-zero has been not so great (I also have sonarr and radarr rename files) and so far its been great!  Its integrated into sonarr and radarr and uses the original filenames you downloaded so you don't have to leave your files with their original name.  It was super easy to set up and I think its definitely the better option.  Here is the section I used for my docker-compose if anyone is interested:

```
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TV}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/complete/tv:/tv
    ports:
      - 6767:6767
```
After starting it up you can reach it at port 6767 and here's a simple guide to get it set up: https://github.com/morpheus65535/bazarr/wiki/Wizard-General

All you really need is your sonarr and radarr API keys and any account information for the subtitle providers you want to use (I use addic7ed and open subtitles) and its set up!
