### ISSUE TITLE
Incorrect media library path for Plex

### ISSUE THREAD

**Issue by blakeinate** [sebgl/htpc-download-box#23]
The path that is provided in the docker-compose configuration for plex is inconsistent with the other provided container configurations. 

To remain consistent with the completed download location of the other containers: 

```
  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
```

Should be 

```
  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/downloads/complete:/data # media library
```
