### ISSUE TITLE
Using arch-delugevpn instead of linuxserver/deluge and dperson/openvpn-client

### ISSUE THREAD

**Issue by csandman** [sebgl/htpc-download-box#31]
I recently switched to unraid and wanted to figure out an easier way to integrate the vpn in this solution and came across [binhex/arch-delugevpn](https://github.com/binhex/arch-delugevpn).  I had issues for a long time setting up this project originally due to the deluge/vpn combo so I figured I would post my alternative setup in case it helps anyone else.  Here is what I replaced the deluge and openvpn docker containers with:

```
version: '3'
services:
  deluge:
    container_name: deluge
    image: binhex/arch-delugevpn:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env 
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - STRICT_PORT_FORWARD=yes
      - VPN_ENABLED=yes
      - VPN_PROV=pia
      - VPN_USER={PIA_USER}
      - VPN_PASS={PIA_PASS}
      - LAN_NETWORK=<lan ipv4 network>
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
      - 8118:8118
      - 58846:58846
      - 58946:58946
```

After that, inside the deluge config folder, I added an `openvpn` folder and added the files mentioned in your guide, without renaming the location file.  [This is the video where I followed the instructions for using this package](https://www.youtube.com/watch?v=5AEzm5y2EvM).  It doesn't use a docker compose but it could still help people with the general setup.

I don't expect you to necessarily change the guide to use this, however if someone else runs into issues with your vpn setup and go to issues to try and figure it out, maybe this could be a helpful alternative!
