### ISSUE TITLE
Using alpine-qbittorrent-openvpn instead of deluge

### ISSUE THREAD

**Issue by SteynGuelen** [sebgl/htpc-download-box#57]
Hi, 

I prefer to use qBittorrent over Deluge. Also, the setup of openvpn/deluge is quite complicated and prone to failure.

Therefore, I used the repo alpine-qbittorrent-openvpn instead of deluge/openvpn. My setup is:
``` 
alpine-qbittorrent-openvpn:
    volumes:
      - ${ROOT}/media/downloads:/downloads
      - ${ROOT}/config/qbittorrent-openvpn:/config
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=netherlands
      - OPENVPN_USERNAME=[redacted]
      - OPENVPN_PASSWORD=[redacted]
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest 
```

This might help other people as well, that have issues with deluge/openvpn.
