### ISSUE TITLE
Add-on: Prowlarr

### ISSUE THREAD

**Issue by cbytestech** [sebgl/htpc-download-box#70]
I've used jackett since starting this venture but switching to prowlarr as part of the -arr suite... best move evarr..see what I did there..
You add an indexer and it can sync directly to the other -arr programs(sonarr, radarr, readarr, etc)
```
#Prowlarr
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:nightly
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - UMASK=002
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/config/prowlarr:/config # config files
      - /media/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download / I added as jackett had it. testing if necessary

```
remember if using root for everything to comment out the PGID and PUID
