### ISSUE TITLE
Sonarr cant find the data folder

### ISSUE THREAD

**Issue by breixopd** [sebgl/htpc-download-box#71]
I cant seem to find the data volume that my plex libraries are tied to on Sonarr, anyone know why?

**Comment by cbytestech** [comment]
which side of the folder var are you changing in the docker-compose.yml?
```
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
```

 Make sure you are editing the left side of the directory..
      - ${ROOT}/config/sonarr: Do not edit this side /config # config files
      - ${ROOT}/complete/tv: Do not edit this side /tv # tv shows folder
      - ${ROOT}/downloads: Do not edit this side /downloads # download folder
      - ${ROOT}/config/plex/db: Do not edit this side /config # plex database
      - ${ROOT}/config/plex/transcode: Do not edit this side /transcode # temp transcoded files
      - ${ROOT}/complete: Do not edit this side /data # media library
