### ISSUE TITLE
Guide: How to make this work from Windows

### ISSUE THREAD

**Issue by binaryPUNCH** [sebgl/htpc-download-box#88]
Just wanted to share my learnings getting this to work on Windows.

Basically, you just need WSL2 and Docker for Windows (configured to use the WSL2 engine).

In the docker-compose.yml file, unfortunately network_mode: `host` doesn't work from Windows, so you will need to remoev that line and expose the ports instead.

This also means that for the containers to talk with each other, you don't use `localhost` or `127.0.0.1` but must use the container name, e.g. `deluge:8112`

I also turned off the VPN since I was having some difficulties, let me/us know if you can get it working. But here is what my end config looks like (also upgraded nzbget with sabnzbd like #86 

```yaml
version: "3.4"
services:
  # vpn:
  #   container_name: vpn
  #   image: dperson/openvpn-client:latest
  #   cap_add:
  #     - net_admin # required to modify network interfaces
  #   restart: unless-stopped
  #   volumes:
  #     - /dev/net:/dev/net:z # tun device
  #     - ${CONFIG_ROOT}/config/vpn:/vpn # OpenVPN configuration
  #   security_opt:
  #     - label:disable
  #   ports:
  #     - 8112:8112 # port for deluge web UI to be reachable from local network
  #   command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    # network_mode: service:vpn # run on the vpn network
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG_ROOT}/config/deluge:/config # config files
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network      

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG_ROOT}/config/jackett:/config # config files
    ports:
      - 9117:9117      

  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG_ROOT}/config/sabnzbd:/config
      - ${ROOT}/complete:/downloads
      # optionally you can also map the incomplete downloads folder, e.g.
      - ${ROOT}/downloads:/incomplete-downloads 
    ports:
    - 8080:8080

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
    - 8989:8989           

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
    - 7878:7878

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    #network_mode: host
    volumes:
      - ${CONFIG_ROOT}/config/plex/db:/config # plex database
      - ${CONFIG_ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
    ports:
    - 32400:32400      

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    #network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG_ROOT}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
    ports:
    - 6767:6767
```
