### ISSUE TITLE
OpenVPN and AirVPN: unrecognized option or missing or extra parameter(s) in data-ciphers

### ISSUE THREAD

**Issue by Nvidix123** [sebgl/htpc-download-box#89]
Hey, thanks for the write-up. This is my first time working on something like this and especially using Docker.

I followed the guide and managed to configure the torrent client but I'm having some issues with the OpenVPN Client.

I put the config files in the exact same spot as in the write-up (/config/vpn) and all the other vpn files, but I get this Error Log when I try to start the VPN docker:

```
> `

myuser@myserver:~/plex$ docker compose up vpn
[+] Running 1/0
 ✔ Container vpn  Created                                                                                                                                                                                0.0s
Attaching to vpn
vpn  | ls: /vpn/*: No such file or directory
vpn  | ls: /vpn/*: No such file or directory
vpn  | The use of ROUTE or -r may no longer be needed, try it without!
vpn  | WARNING: ip6tables disabled!
vpn  | Run 'sudo modprobe ip6table_filter' on your host
vpn  | modprobe: can't change directory to '/lib/modules': No such file or directory
vpn  | modprobe: can't change directory to '/lib/modules': No such file or directory
vpn  | ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
vpn  | Perhaps ip6tables or your kernel needs to be upgraded.
vpn  | modprobe: can't change directory to '/lib/modules': No such file or directory
vpn  | modprobe: can't change directory to '/lib/modules': No such file or directory
vpn  | ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
vpn  | Perhaps ip6tables or your kernel needs to be upgraded.
vpn  | The use of ROUTE or -r may no longer be needed, try it without!
vpn  | Dump terminated
vpn  | ERROR: VPN not configured!
`

```
This is my Docker Compose File, which is saved in /home/myuser/plex:
`
```
version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/config/vpn/ # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: "-r 192.168.0.0/24" # route local network traffic
   

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
     
```

and for the vpn.conf I just used the generated one from AirVPN, making sure that I put all the other necessary files in the same folder (/config/vpn)
